apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: database-persistant-volume-claim
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: "local-storage"
  resources:
     requests:
       storage: 0.2Gi
